server:
  port: 8091
spring:
  application:
    name: api-gateway
zuul:
  routes:
    user-service: /user-service/**
  prefix: /api # 这里是映射路径
      #path: /user-service/** # 这里是映射路径
      # url: http://127.0.0.1:8088 使用eureka来代替写死的url
      # serviceId: user-service # 指定服务名称
eureka:
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka # 映射路径对应的实际url地址
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000