server:
  port: 8088
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://120.78.172.84:3306/zkdb
    username: root
    password: mojay0118
mybatis:
  type-aliases-package: cn.zk
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka
 instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找